recipe/meta.yaml

bump version to 0.17.4

---

recipe/meta.yaml

bump version to 0.18.1

---

recipe/meta.yaml

bump version to 0.19.1

---

recipe/meta.yaml

This PR adds @jrbourbeau as a maintainer
Checklist

Add @jrbourbeau as maintainer

---

recipe/meta.yaml

Require Python 3.6 or above

---

README.md
recipe/meta.yaml

dask-core v2.13.0

---

recipe/meta.yaml

Release 2021.06.2

---

.gitattributes
.scripts/run_docker_build.sh
README.md
build-locally.py
recipe/meta.yaml

Release 2021.11.0

---

recipe/meta.yaml

Upgrade to the latest Dask release using grayskull. Accept some (though not all) of the changes grayskull makes. Not all of them make sense in this context.
Checklist

Release 2021.11.1 (with grayskull)

---

.azure-pipelines/azure-pipelines-linux.yml
.ci_support/linux_64_.yaml
.scripts/build_steps.sh
recipe/meta.yaml

Release 2021.12.0

---

recipe/meta.yaml

Release 2022.01.1

---

LICENSE.txt
recipe/meta.yaml

Release 2022.02.0

---

README.md
recipe/meta.yaml

Release 2022.03.0

---

README.md
recipe/meta.yaml

Release 2022.04.0

---

.circleci/config.yml
.scripts/build_steps.sh
LICENSE.txt
build-locally.py
recipe/meta.yaml

Release 2022.6.1

---

recipe/meta.yaml

Checklist
Fixes https://github.com/conda-forge/dask-core-feedstock/issues/135

Revert to template friendly source URL

---

recipe/meta.yaml

Release 2022.10.2

---

recipe/meta.yaml

Thanks for helping out with the release issues @charlesbluca. Just chatted with @mrocklin about giving you more permissions here.

Add @charlesbluca as a maintainer

---

.scripts/build_steps.sh
README.md
recipe/meta.yaml

Checklist
Closes https://github.com/conda-forge/dask-core-feedstock/issues/164

Release 2023.3.2

---

recipe/meta.yaml

Release 2023.4.0

---

recipe/meta.yaml

Release 2023.5.0

---

.azure-pipelines/azure-pipelines-linux.yml
recipe/meta.yaml

Release 2023.8.0

---

recipe/meta.yaml

Release 2023.12.0

---

recipe/meta.yaml

Add fjetter to maintainers

---

recipe/recipe.yaml

I was unable to merge #243 as I'm not listed as a maintainer here, adding myself now. Thanks for getting things merged in the meantime @TomAugspurger.

Add @jacobtomlinson as a maintainer
